<?php

/**
 * @file
 * Embeds the Nomensa Accessibile Media Player within Drupal.
 */

require 'includes/core.inc';

/**
 * Implements hook_menu().
 */
function nomensa_amp_menu() {
  $items['admin/config/media/nomensa-amp'] = array(
    'title' => 'Nomensa Accessible Media Player',
    'description' => 'Administration functions for the Nomensa Accessible Media Player module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nomensa_amp_admin_settings_form'),
    'access arguments' => array('administer nomensa amp'),
    'file' => 'includes/nomensa_amp.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function nomensa_amp_permission() {
  return array(
    'administer nomensa amp' => array(
      'title' => t('Administer the Nomensa Accessible Media Player module.'),
    ),
  );
}

/**
 * Implements hook_init().
 */
function nomensa_amp_init() {
  if ($amp_settings = variable_get('nomensa_amp_settings') && $path = libraries_get_path('nomensa_amp')) {
    foreach ($amp_settings['players'] as $player => $enabled) {
      // If enabled, do something.
    }
  }
}
