<?php

/**
 * @file
 * Integrates the Nomensa Accessible Media Player with Drupal.
 */

/**
 * Implementation of hook_menu().
 */
function nomensa_amp_menu() {
  $items['admin/settings/nomensa-amp'] = array(
    'title' => 'Nomensa Accessible Media Player',
    'description' => 'Administration settings for the Nomensa Accessible Media Player module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nomensa_amp_admin_settings_form'),
    'access arguments' => array('administer nomensa amp'),
    'file' => 'nomensa_amp.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function nomensa_amp_perm() {
  return array('administer nomensa amp');
}

/**
 * Implementation of hook_init().
 */
function nomensa_amp_init() {
  $settings = variable_get('nomensa_amp_settings', NULL);
  $library_path = libraries_get_path('nomensa_amp');

  // Add the jQuery UI slider.
  jquery_ui_add('ui.slider');

  // Add global CSS and javascript files.
  drupal_add_js($library_path . '/core/javascript/swfobject/swfobject.js');
  drupal_add_js($library_path . '/custom/javascript/jquery.loader.js');

  if (isset($settings['advanced']['minimised']) && $settings['advanced']['minimised'] == 1) {
    // Load the minimised files.
    drupal_add_js($library_path . '/core/javascript/jquery.player.min.js');
    drupal_add_css($library_path . '/core/css/player-core.min.css');
    drupal_add_css($library_path . '/custom/css/player-theme.min.css');
  }
  else {
    // Load the normal files.
    drupal_add_js($library_path . '/core/javascript/jquery.player.js');
    drupal_add_css($library_path . '/core/css/player-core.css');
    drupal_add_css($library_path . '/custom/css/player-theme.css');
  }

  if (isset($settings['players'])) {
    foreach ($settings['players'] as $player => $enabled) {
      // Add player-specific files.
      if ($enabled) {
        switch ($player) {
          case 'vimeo':
            drupal_add_js($library_path . '/custom/javascript/config/vimeo/vimeo.config.js');
            break;

         case 'jwplayer':
            drupal_add_js($library_path . '/custom/javascript/config/jwplayer-5/core/jwplayer.js');
            drupal_add_js($library_path . '/custom/javascript/config/jwplayer-5/jw-player.config.js');
            break;
        }
      }
    }
  }
}

/**
 * Implementation of hook_requirements().
 */
function nomensa_amp_requirements($phase) {
  $requirements = array();
  $t = get_t();

  if ($phase == 'runtime') {
    $library_path = libraries_get_path('nomensa_amp');
    $requirements['nomensa_amp'] = array(
      'title' => $t('Nomensa Accessible Media Player'),
    );

    if (!is_dir($library_path)) {
      // Library not found.
      $requirements['nomensa_amp']['value'] = $t('Not Found');
      $requirements['nomensa_amp']['severity'] = REQUIREMENT_ERROR;
      $requirements['nomensa_amp']['description'] = $t('The Nomensa AMP library cannot be found. <a href="https://github.com/nomensa/Accessible-Media-Player" title="Nomensa Accessible Media Player">Download it</a> and extract it into <em>sites/all/libraries/nomensa_amp</em>.');
    }
    else {
      if (!$settings = variable_get('nomensa_amp_settings', NULL)) {
        // Not configured.
        $requirements['nomensa_amp']['value'] = $t('Not configured');
        $requirements['nomensa_amp']['severity'] = REQUIREMENT_ERROR;
        $requirements['nomensa_amp']['description'] = $t('The module has been enabled, but no video players have been enabled.');
      }
      else {
        // Check to see if any video players have been enabled.
        $configured = in_array('1', $settings['players']);

        if ($configured) {
          // All OK.
          $requirements['nomensa_amp']['value'] = $t('Enabled');
          $requirements['nomensa_amp']['severity'] = REQUIREMENT_OK;
        }
        else {
          // Not configured.
          $requirements['nomensa_amp']['value'] = $t('Not configured');
          $requirements['nomensa_amp']['severity'] = REQUIREMENT_ERROR;
          $requirements['nomensa_amp']['description'] = $t('The module has been enabled, but no video players have been enabled.');
        }
      }
    }
  }

  return $requirements;
}

